# This file configures the GitHub Pages site.
# It uses the "minimal" theme and sets your project title.
theme: jekyll-theme-minimal
title: PARMCO - Phone App RP4 Motor Control
description: Group 5 (Liam Dabelstein, Jake VanEssendelft) - ECSE 4235 Final Project
